@{
'$this.Icon' = New-Object -TypeName System.Drawing.Icon -ArgumentList @(New-Object -TypeName  System.IO.MemoryStream -ArgumentList @(,[System.Convert]::FromBase64String('AAABAAEAEBAAAAEAGABoAwAAFgAAACgAAAAQAAAAIAAAAAEAGAAAAAAAQAMAAAAAAAAAAAAAAAAAAAAA
        AACOhnyKgXaIf3KHfW6Fe215cGNyaV4AAAAAAAAAAADflAXflAXflAXflAUAAAAAAACqopi0qpuwp5mr
        oZMA4kIA/0d7c2YAAAAAAAAAAAAAAADflAXflAXflAUAAAAAAAC2sKa5r6G1rJ2vpZdR66sf685+dWcA
        AAAAAAAAAAAAAADflAXflAXflAUAAAAAAAC8t6/Cuau/tqi4r6G1rJ6yqJqBd2kAAAAAAAAAAADflAUA
        AAAAAADflAUAAAAAAAC/urPGva/Euqy9tKa6saO2raCDeWsAAAAAAADflAUAAAAAAAAAAAAAAAAAAAAA
        AADBvbjJwbLIvrDDuau/tqi7s6WFe2zflAXflAUAAAAAAAAAAAAAAADflAUAAAAAAADEwLvKwbPKwbPG
        va/EuqzBuKqHfW/flAXflAUAAAAAAAAAAAAAAADflAXflAUAAADGw8CUjIOFfnZ4cml/d26KgXaLgHHf
        lAXflAXflAXflAXflAXflAXflAXflAXflAXIxsLw7ePw7ePt6t/s6Nzq59qPhHXflAUAAAAAAAAAAAAA
        AAAAAADflAXflAUAAADLyMXw7ePw7ePt6uDs6N3q59qUiXrflAUAAAAAAAAAAAAAAAAAAADflAUAAAAA
        AADLyceinpiKhoF8dW6Ce3KMg3eaj38AAADflAUAAAAAAAAAAAAAAAAAAAAAAAAAAADMysj29Oz18+no
        5dTk387g28qfloYAAAAAAADflAUAAAAAAAAAAAAAAAAAAAAAAADMysj59+/49+7r6dzo5dTh3MumnI0A
        AAAAAAAAAADflAUAAAAAAADflAUAAAAAAADMysjTzblcTiYzMzEzMzHTzbmqoZMAAAAAAAAAAAAAAADf
        lAXflAXflAUAAAAAAADMysjMysjKycbBvLe7ta20rKKspJcAAAAAAAAAAAAAAADflAXflAXflAUAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADflAXflAXflAXflAUAAAAAAAABwwAAAeMAAAHj
        AAAB2wAAAb8AAAB7AAAAeQAAAAAAAAD5AAAA+wAAAX8AAAG/AAAB2wAAAeMAAAHjAAD/wwAA')));
}